E_learning/account/routes.py
from flask import Blueprint
from E_learning import db, app
from .form import UpdateAccount
from E_learning .models import User
from flask_login import current_user, login_required
from E_learning .img_utils.utility import save_picture
from flask import flash, redirect, render_template, request, url_for, request



user_account = Blueprint('user_account', __name__)



@user_account.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccount()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data #this scrip is resp to change email and username
        current_user.email = form.email.data #<^>
        db.session.commit()
        flash('Your account has been updated!', category='success')
        return redirect(url_for('dashbrd.dashboard'))
    elif request.method == 'GET':
        form.username.data = current_user.username #this script helps by repopulating the email usrname into the form
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('edit-profile.html', image_file=image_file, form=form)

E_learning/authentication/routes.py
from flask import Blueprint
from flask_mail import Message
from E_learning import db, bcrypt, mail
from flask import get_flashed_messages
from E_learning .models import User, Mybook
from flask import flash, redirect, render_template, request, url_for, request
from flask_login import login_user, logout_user, current_user, login_required
from .form import RegisterForm, LoginForm, RequestResetForm, ResetPasswordForm, Studentbrq


authent = Blueprint('authent', __name__)



@authent.route('/signup', methods=['GET', 'POST'])
def signup():
    form = RegisterForm()
    if form.validate_on_submit():
        hashed_pwd = bcrypt.generate_password_hash(form.password.data)
        user = User(index=form.index.data,  username=form.username.data, email=form.email.data, password=hashed_pwd)
        db.session.add(user)
        db.session.commit()
        flash(f'Account created successfully {user.email}', category='success')
        return redirect(url_for('authent.login'))
    if form.errors != {}:
        for err_msg in form.errors.values():
            flash(f'Registration unsuccessful {err_msg}', category='error')
    return render_template('signup_.html', form=form)
 


@authent.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(index=form.index.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            flash(f'Successfully logged in as {user.index}', category='success')
            return redirect(url_for('dashbrd.dashboard'))
        else:
            flash('Login Uncessful. Please check email and password', category='error')
    return render_template('login.html', form=form)




@authent.route('/bkrequest', methods=['GET', 'POST'])
def  bkrequest():
    form = Studentbrq()
    if form.validate_on_submit():
        usrb = Mybook(the_title=form.the_title.data, thebook_auth=form.thebook_auth.data, 
                                        dpment=form.dpment.data, author=current_user)
        db.session.add(usrb)
        db.session.commit()
        flash(f'Your request has been submited! you will receive the feedback', category='success')
        return redirect(url_for('dashbrd.dashboard'))
    if form.errors != {}:
        for err_msg in form.errors.values():
            flash(f"Oops there's a problem! try again {err_msg}", category='error')
    return render_template('bookrequest.html', form=form)
    



def send_reset_email(user):
    token = user.get_reset_token()
    msg = Message('Password Reset Request', sender='geniusitg@gmail.com', recipients=[user.email])
    msg.body =  f''' To reset your password, visit the following link: {url_for('authent.reset_token', 
    token=token, _external=True)}
    If you did not make this request then simply ignore this email and no changes will be made. '''
    mail.send(msg) 


@authent.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password', category='info')
        return redirect(url_for('authent.login'))
    return render_template('reset_request.html', form=form)


@authent.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', category='warning')
        return redirect(url_for('reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_pwd = bcrypt.generate_password_hash(form.password.data)
        user.password = hashed_pwd
        db.session.commit()
        flash(f'Your password has been update! You are now able to log in', category='success')
        return redirect(url_for('authent.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)



@authent.route('/logout')
def logout():
    logout_user()
    flash('You have been logged out successfuly', category='success')
    return render_template('home.html')

E_learning/studentsadmin_/routes.py
import os
from flask import Blueprint
from E_learning import db, app
from flask_login import login_required, current_user
from E_learning .img_utils.utility import save_picture
from .form import Sbookupload, Allbooks, Approvebook
from E_learning .models import User, Bokitems, Mybook, Bokitems
from flask import render_template, flash, request, redirect, url_for, send_from_directory



dashbrd = Blueprint('dashbrd', __name__)



@dashbrd.route('/htuADmin2022', methods=['POST', 'GET'])
@login_required
def htuADmin2022():
    if request.method == 'GET':
        query = request.args.get('query')     
        post = Bokitems.query.filter(Bokitems.stb_title.like('%' + str(query)+ '%')).all()
        flash(f'You have searched for {query}', category='success' )
    else:
        flash("Your search doesn't much the request", category='danger')
    return render_template('adminlog.html', posts=post , query=query)




@dashbrd.route('/dashboard', methods=['GET', 'POST'])
@login_required
def dashboard():
    student_books = Bokitems.query.all()
    if request.method == 'GET':
        query = request.args.get('query')
        posts = Bokitems.query.filter(Bokitems.stb_title.like('%' + str(query) + '%')).all()
    return render_template('dashboard.html', student_books=student_books, posts=posts, query=query)



@dashbrd.route('/addbook', methods=['GET', 'POST'])
@login_required
def addbook():
    form = Sbookupload()
    if form.validate_on_submit():
        usrb = Bokitems(stb_title=form.stb_title.data,  th_auth=form.th_auth.data,  
                                            my_category=form.my_category.data, 
                                            nm_issuerer=form.nm_issuerer.data, 
                                            author=current_user, bok_profile=save_picture(form.bok_profile.data))
        db.session.add(usrb)
        db.session.commit()
        flash('Your data has been added to the system', category='success')
        return redirect(url_for('dashbrd.htuADmin2022'))
    if form.errors !={}:
        for err_msg in form.errors.values():
            flash(f'Your request was not sent please try again {err_msg}', category='error')
    return render_template('addbook.html', form=form)



@dashbrd.route('/allbooks')
@login_required
def allbooks():
    form = Allbooks()
    student_books = Bokitems.query.order_by(Bokitems.id.desc()).all()
    return render_template('allbooks.html', form=form, student_books=student_books)



@dashbrd.route('/approve')
@login_required
def approve():
    form = Approvebook()
    users = User.query.all()
    return render_template('approve.html', form=form, users=users)



@dashbrd.route('/request_all')
@login_required
def request_all():
    students = Mybook.query.order_by(Mybook.date_request.desc()).all()
    dir(students)
    return render_template('request_all_book.html', students=students)

E_learning/views/routes.py
from E_learning import db
from flask import Blueprint
from E_learning import bcrypt
from .form import ContactForm
from E_learning .models import Bokitems
from flask_login import login_user, current_user
from E_learning .models import User, Suggestion_Contact
from flask import render_template, request, url_for, flash, redirect



view = Blueprint('view', __name__)


@view.route('/')
@view.route('/home', methods=['GET', 'POST'])
def home():
    return render_template('home.html')



@view.route('/books')
def books():
    return render_template('books.html')



@view.route('/mechanical')
def mechanical():
    redirect('view.dashboard')
    return render_template('mech.html')



@view.route('/fashion')
def fashion():
    redirect('view.dashboard')
    student_books = Bokitems.query.all()
    return render_template('fahiondepart.html', student_books=student_books)


 
@view.route('/contact', methods=['GET', 'POST'])
def contact():
    form = ContactForm()
    if form.validate_on_submit():
        cont = Suggestion_Contact(name=form.name.data, student_id=form.student_id.data, 
                                                                subject=form.subject.data, 
                                                                phone_number=form.phone_number.data, 
                                                                text_area=form.text_area.data, author=current_user)
        db.session.add(cont)
        db.session.commit()
        flash('Thanks for your suggestion our team will work on it', category='success')
        return redirect(url_for('view.home'))
    return render_template('contact.html', form=form)



@view.route('/about')
def about():
    return render_template('about.html')

E_learning/templates/404_error_page.html

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</head>
<body>
    <br><br>
    <div class="container">
    <div class="container">
        <h1>Opps this page does not exist ):</h1>
    <div class="spinner-grow text-primary" role="status">
        
        <span class="visually-hidden">Loading...</span>
    </div>
    <div class="spinner-grow text-secondary" role="status">
        <span class="visually-hidden">Loading...</span>
    </div>
    <div class="spinner-grow text-success" role="status">
        <span class="visually-hidden">Loading...</span>
    </div>
    <div class="spinner-grow text-danger" role="status">
        <span class="visually-hidden">Loading...</span>
    </div>
    <div class="spinner-grow text-warning" role="status">
        <span class="visually-hidden">Loading...</span>
    </div>
    <div class="spinner-grow text-info" role="status">
        <span class="visually-hidden">Loading...</span>
    </div>
    <div class="spinner-grow text-light" role="status">
        <span class="visually-hidden">Loading...</span>
    </div>
    <div class="spinner-grow text-dark" role="status">
        <span class="visually-hidden">Loading...</span>
    </div>
    </div>
    <br>
    <a href="{{ url_for('view.home')}}"><button class="btn btn-info">Back home</button></a>
    </div>
</body>
</html>

E_learning/templates/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    {% block head %}
    <title>{% block title %}Login{% endblock %}</title>

    <!-- Custom fonts for this template-->
    <link rel="stylesheet" href="{{url_for('static', filename='vendor/fontawesome-free/css/all.min.css')}}"
      type="text/css"/>

    <link rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"/>

    <!-- Custom styles for this template-->
    <link rel="stylesheet" href="{{url_for('static', filename='css/sb-admin-2.min.css')}}"/>

    <!-- Custom bootsrap Styling -->
    <link rel="stylesheet" href="{{ url_for('static', filename='/bootstrap-5.1.3/css/bootstrap.min.css')}}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='/bootstrap-5.1.3/js/bootstrap.min.js')}}"/>

    <link rel="stylesheet" href="{{ url_for('static', filename='/bootstrap-4.1.3/css/bootstrap.min.css')}}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='/bootstrap-4.1.3/js/bootstrap.min.js')}}"/>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>

    {% endblock %}
  </head>
  <body class="bg-gradient-primary">
    {% block content %}

    {% with messages = get_flashed_messages(with_categories=True) %} 
      {% if messages %} {% for category, message in messages %} 
      {% if category == "error" %}

      <div class="alert alert-danger alter-dismissable fade show" role="alert">
        {{ message }}
        <button class="close" data-dismiss="alert" type="button">&times;</button>
      </div>

      {% else %}
      <div class="alert alert-success alter-dismissable fade show" role="alert">
        {{ message }}
        <button class="close" data-dismiss="alert" type="button">&times;</button>
      </div>
    {% endif %}{% endfor %}{% endif %}{% endwith %}

    <div class="container">
      <div class="row justify-content-center">
        <div class="col-xl-10 col-lg-12 col-md-9">
          <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
              <!-- Nested Row within Card Body -->
              <div class="row">
                <div class="col-lg-6 d-none d-lg-block">
                  <img src="{{url_for('static', filename='img/gh.jpg')}}">
                </div>
                <div class="col-lg-6">
                  <div class="p-5">
                    <div class="text-center">
                      <h1 class="h4 text-gray-900 mb-4"><strong>Login</strong></h1>
                    </div>
                    <form action="" method="POST">
                      {{ form.hidden_tag() }} 
                      {{ form.index(class='form-control') }}
                      <br />
                      {{ form.password(class='form-control') }}
                      <br />
                      {{ form.remember(class='form-check-input') }} 
                      {{ form.remember.label(class="form-check-label") }}
                      <br />
                      {{ form.submit(class='btn btn-primary btn-user btn-block') }}
                      <hr />
                      <a href="https://accounts.google.com"
                        target="_blank" class="btn btn-google btn-user btn-block">
                        <i class="fab fa-google fa-fw"></i>Login with Google
                      </a>
                    </form>

                    <hr />
                    <div class="text-center">
                      <a class="small" href="{{ url_for('authent.reset_request')}}">Forgot Password?</a>
                    </div>

                    <div class="text-center"><a class="small" href="{{ url_for('authent.signup')}}">
                        Create an Account!</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{{url_for('static', filename='vendor/jquery/Jquery.min.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{{url_for('static', filename='vendor/jquery-easing/jquery.easing.min.js')}}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{{url_for('static', filename='js/sb-admin-2.min.js')}}"></script>
    {% endblock %}
  </body>
</html>

E_learning/templates/master.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta content="IE=edge" http-equiv="X-UA-Compatible" />
    <meta
      content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport"/>
    <meta content="" name="description" />
    <meta content="" name="author" />

    <title>E-Learning M-S</title>

    <!-- Custom fonts for this template-->
    <link
      href="{{url_for('static', filename='vendor/fontawesome-free/css/all.min.css')}}"rel="stylesheet" type="text/css"/>

    <link
      href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
      rel="stylesheet"/>

    <!-- Custom styles for this template-->
    <link
      href="{{url_for('static', filename='css/sb-admin-2.min.css')}}" rel="stylesheet"/>
  </head>

  <body id="page-top">
    <!-- Page Wrapper  and side bar -->
    <div id="wrapper">
      <ul
        class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion"id="accordionSidebar">
        <a class="sidebar-brand d-flex align-items-center justify-content-center"href="#">
          <div class="sidebar-brand-icon">
            <img
              src="{{ url_for('static', filename='/images/patnar-logo/p-2.png')}}"width="50" height="50" alt="logo"/>
          </div>
        </a>

        <hr class="sidebar-divider my-0" />
        <li class="nav-item active">
          <a class="nav-link" href="">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Student Dashboard</span>
          </a>
        </li>

        <hr class="sidebar-divider" />
        <div class="sidebar-heading"><strong>Departments</strong></div>
        <li class="nav-item">
          <a aria-controls="collapsePages" aria-expanded="true" class="nav-link collapsed"
            data-target="#collapsePages" data-toggle="collapse"href="#">
            <i class="fas fa-fw fa-folder"></i>
            <span>Choose deparment</span>
          </a>

          <div aria-labelledby="headingPages" class="collapse" data-parent="#accordionSidebar" id="collapsePages">
            <div class="bg-white py-2 collapse-inner rounded">
              <a class="collapse-item" id="stu" href="{{ url_for('dashbrd.dashboard')}}">Computer Sci Dep</a>
              <a class="collapse-item" href="{{ url_for('view.fashion')}}">Fashion Dep</a>
              <a class="collapse-item" href="{{ url_for('view.mechanical')}}">Mechanical Eng Dep</a>
            </div>
          </div>

        <hr class="sidebar-divider"/>
        <div class="sidebar-heading">Book Request</div>
        <!-- Nav Item - Pages Collapse Menu -->
        <li class="nav-item">
          <a aria-controls="collapseone" aria-expanded="true" class="nav-link collapsed"
              data-target="#collapseone"data-toggle="collapse"href="#">
              <i class="fas fa-fw fa-cog"></i>
              <span>Resquest For Book</span>
          </a>
          <div aria-labelledby="headingTwo"
            class="collapse" data-parent="#accordionSidebar" id="collapseone">
            <div class="bg-white py-2 collapse-inner rounded">
              <a class="collapse-item" href="{{ url_for('authent.bkrequest')}}">Send a request</a>
            </div>
          </div>
        </li>


        <hr class="sidebar-divider" />
        <div class="sidebar-heading">Personal Info</div>
        <!-- Nav Item - Pages Collapse Menu -->
        <li class="nav-item">
          <a aria-controls="collapseTwo" aria-expanded="true" class="nav-link collapsed"
              data-target="#collapseTwo"data-toggle="collapse"href="#">
              <i class="fas fa-fw fa-cog"></i>
              <span>Account Settings</span>
          </a>

          <div aria-labelledby="headingTwo"
            class="collapse" data-parent="#accordionSidebar" id="collapseTwo">
            <div class="bg-white py-2 collapse-inner rounded">
              <a class="collapse-item" href="{{ url_for('user_account.account')}}">Update Account</a>
            </div>
          </div>
        </li>

        <hr class="sidebar-divider d-none d-md-block" />
        <div class="text-center d-none d-md-inline">
          <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>
      </ul>

      <!-- Top search and navbar -->
      <div class="d-flex flex-column" id="content-wrapper">
        <div id="content">
          <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
            <button class="btn btn-link d-md-none rounded-circle mr-3" id="sidebarToggleTop">
              <i class="fa fa-bars"></i>
            </button>

            <form action="" autocomplete="on" method="GET" class="w-100 m-0" style="padding-right: 20%">
              <div class="input-group-append rounded-left">
                <input type="input" class="form-control rounded-left form-control-sm"autocomplete="on"
                  style="float: left; border-radius: 0" name="query" placeholder="What you want..."/>
                <button
                  class="btn btn-primary btn-sm rounded-right" 
                  style="border-radius: 0"type="submit">Search
                </button>
              </div>
            </form>

            <ul class="navbar-nav ml-auto">
              <!-- Nav Item - Search Dropdown (Visible Only XS) -->
              <li class="nav-item dropdown no-arrow d-sm-none">
                <a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle"
                  data-toggle="dropdown" href="#"id="searchDropdown"role="button">
                  <i class="fas fa-search fa-fw"></i>
                </a>
                <!-- Dropdown - Messages -->
                <div aria-labelledby="searchDropdown"
                  class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in">
                  <form action="" autocomplete="on" method="GET" class="w-100 m-0" style="padding-right: 20%">
                    <div class="input-group-append rounded-left">
                      <input type="input" class="form-control rounded-left form-control-sm"autocomplete="on"
                        style="float: left; border-radius: 0" name="query" placeholder="What you want..."/>
                      <button
                        class="btn btn-primary btn-sm rounded-right" 
                        style="border-radius: 0"type="submit">Search
                      </button>
                    </div>
                  </form>
                </div>
              </li>

              <!-- Nav Item - Alerts -->
              <li class="nav-item dropdown no-arrow mx-1">
                <a aria-expanded="false" aria-haspopup="true"
                  class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="alertsDropdown"role="button">
                  <i class="fas fa-bell fa-fw"></i>
                  <span class="badge badge-danger badge-counter">3+</span>
                </a>

                <div aria-labelledby="alertsDropdown" class="
                    dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in">
                  <h6 class="dropdown-header">Alerts Center</h6>
                  <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="mr-3">
                      <div class="icon-circle bg-primary">
                        <i class="fas fa-file-alt text-white"></i>
                      </div>
                    </div>

                    <div>
                      <div class="small text-gray-500">December 12, 2019</div>
                      <span class="font-weight-bold">A new monthly report is ready to download!</span>
                    </div>
                  </a>

                  <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="mr-3">
                      <div class="icon-circle bg-success">
                        <i class="fas fa-donate text-white"></i>
                      </div>
                    </div>

                    <div>
                      <div class="small text-gray-500">December 7, 2019</div>
                      $290.29 has been deposited into your account!
                    </div>
                  </a>
                  <a class="dropdown-item text-center small text-gray-500" href="#" >Show All Alerts</a>
                </div>
              </li>

              <!-- Nav Item - Messages -->
              <li class="nav-item dropdown no-arrow mx-1">
                <a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle"
                  data-toggle="dropdown" href="#"id="messagesDropdown"role="button">
                  <i class="fas fa-envelope fa-fw"></i>
                  <span class="badge badge-danger badge-counter">7+</span>
                </a>

                <div aria-labelledby="messagesDropdown"
                  class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in">
                  <h6 class="dropdown-header">Message Center</h6>
                  <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                      <img alt="..." class="rounded-circle" src="{{url_for('static', filename='img/undraw_profile_1.svg')}}"/>
                      <div class="status-indicator bg-success"></div>
                    </div>

                    <div class="font-weight-bold">
                      <div class="text-truncate">
                        Hi there! I am wondering if you can help me with a
                        problem I've been having.
                      </div>
                      <div class="small text-gray-500">Emily Fowler · 58m</div>
                    </div>
                  </a>

                  <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                      <img alt="..." class="rounded-circle"src="{{url_for('static', filename='img/undraw_profile_2.svg')}}"/>
                      <div class="status-indicator"></div>
                    </div>

                    <div>
                      <div class="text-truncate">
                        I have the photos that you ordered last month, how would
                        you like them sent to you?
                      </div>
                      <div class="small text-gray-500">Jae Chun · 1d</div>
                    </div>
                  </a>
                  <a
                    class="dropdown-item text-center small text-gray-500"
                    href="#">Read More Messages</a>
                </div>
              </li>

              <div class="topbar-divider d-none d-sm-block"></div>
              <!-- Nav Item - User Information -->
              <li class="nav-item dropdown no-arrow">
                <a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle"
                  data-toggle="dropdown" href="#" id="userDropdown"role="button">
                  <span class="mr-2 d-none d-lg-inline text-gray-600 small"></span>
                  <img class="img-profile rounded-circle" 
                    src="{{ image_file }}" width="90" height="60"/>
                </a>

                <!-- Dropdown - User Information -->
                <div aria-labelledby="userDropdown"
                  class="dropdown-menu dropdown-menu-right shadow animated--grow-in">
                  <a class="dropdown-item">
                    <h6 class="account-heading">{{ current_user.username }}</6>
                  </a>

                  <hr>
                  <a class="dropdown-item">
                    <p class="text-secondary">{{ current_user.email}}</p>
                  </a>

                  <div class="dropdown-divider"></div>
                    <a class="dropdown-item" data-target="#logoutModal" data-toggle="modal"href="">
                      <a class="dropdown-item" href="{{ url_for('authent.logout')}}">
                      <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>Logout
                    </a>
                </div>
              </li>
            </ul>
          </nav>

          <!-- navbar inheritance -->
          <div class="container-fluid">
            {%block container%} 
            {% endblock %}
          </div>
        </div>

        <!-- Footer -->
        <footer class="sticky-footer bg-white">
          <div class="container my-auto">
            <div class="copyright text-center my-auto">
              <span >All Rights Reserved 2021 @
                <a href="https://htu.edu.gh/" target="_blank">Ho Technical University</a>
              </span>
            </div>
          </div>
        </footer>
      </div>
    </div>

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>

    <!-- Bootstrap core JavaScript-->
    <script src="{{url_for('static', filename='vendor/jquery/jquery.min.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{{url_for('static', filename='vendor/jquery-easing/jquery.easing.min.js')}}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{{url_for('static', filename='js/sb-admin-2.min.js')}}"></script>

    <!-- Page level plugins -->
    <script src="{{url_for('static', filename='vendor/chart.js/Chart.min.js')}}"></script>

    <!-- Page level custom scripts -->
    <script src="{{url_for('static', filename='js/demo/chart-area-demo.js')}}"></script>
    <script src="{{url_for('static', filename='js/demo/chart-pie-demo.js')}}"></script>
  </body>
</html>